### ISSUE TITLE
Take-up wheel yanks the film while reeling it in

### ISSUE THREAD

**Issue by jkytomaki** [jareff-g/ALT-Scann8#45]
I believe the latest changes to the Arduino code and stepper motor control made the take-up wheel behave erratically. Instead of keeping a steady tensions to the film, it now often yanks the film - pulls it and then releases it, rolling backwards - while reeling it in.

**Comment by jareff-g** [comment]
I just had a look at this one and have a couple of comments:

1 - One important factor to be considered here is clearance: We have clearance between the motor's beveled axis and the reel support, and between the reel support and the reel itself. This can be checked by locking the motors (clicking on 'lock reels' button until reels are locked) and trying to ,move it manually. It can be seen that it can be moved by 20-30º without forcing the motor. I'm no physicist, but I guess that clearance means that when the motor stops, the reel will still move forward a few degrees, and when the clearance is exhausted (reel hits reel support, reel support hits motor beveled axis), the reel will bounce back, moving in the opposite direction a few degrees. Clearance on the motor axis can be reduced by adding a tiny bit of thin paper between the motor axis and the reel support (I just did it), and even if it is tighter when moving by hand, the effect is still there (true, to a lower degree).

2 - Besides the clearance issue, I have checked that while the take-up reel is moving, it is posible to manually stop it or slow it down, without applying to much force. I honestly don't know if it is possible to make the motor to have a stronger movement, either by setting up the A4988 driver (some instructions [here](https://youtu.be/89BHS9hfSUk)) or using some other method. Any suggestion is welcome.

For now I'll leave this one opened, since anyway I wanted to review the take-up algorithm (not an easy one), maybe some ides arrrive in the meantime.

**Comment by jkytomaki** [comment]
For me, the issue happens sporadically. For a while the tension of the film is kept, then for a while the take-up wheel janks the film. See the two videos below for examples of both behaviour. When the wheel is acting "normally", sure I can force it to roll counter-clockwise without too much force, but it's still keeping enough tension to not reel back at all after stopping.

https://github.com/jareff-g/ALT-Scann8/assets/6197808/7defa9a4-5903-4620-ae64-4233bd068caf

https://github.com/jareff-g/ALT-Scann8/assets/6197808/1732250e-6234-4c5f-9111-cb1cd1f7bc19

**Comment by jkytomaki** [comment]
> One important factor to be considered here is clearance: We have clearance between the motor's beveled axis and the reel support, and between the reel support and the reel itself

Just adding a note, that my take-up reel was using the original T-Scann 8 reel support, that doesn't have any "play" and fits the motor's axis very tightly. I was also using a pretty tight adapter for the reel, so there wasn't any play or clearance between the motor and the support, or between the support and the reel. I now replaced the T-Scann 8 support with your version, and noticed that it doesn't fit the motor quite so tightly. But clearance/play wasn't the original issue here - the motor seems to release it's lock causing it to bounce back.

**Comment by jareff-g** [comment]
> But clearance/play wasn't the original issue here - the motor seems to release it's lock causing it to bounce back.

That's correct, as I said in point 2, but in my case the play between the different elements amplifies the effect.

**Comment by jareff-g** [comment]
The changes I have just committed should solve that problem. It was a side effect of the changes done recently to have all reels in neutral by default (when no action is ongoing). And not only that, I have found the root issue that was causing the take-up action to be erratic at times, especially when changing the scan speed.
Now it should be more consistent, not putting too much tension on the film (which means pinch roller is mandatory).
Please close if OK for you.

**Comment by jareff-g** [comment]
Adding video showing take-up as of ALT-Scann8 1.10.0:
!()[https://github.com/jareff-g/ALT-Scann8/assets/98735354/582a9532-f46b-4a70-931a-1772f338771b]
